# Question 1

In [2]:
import numpy as np


a=np.array([33,22,11])

b=np.array([10,20,30])

print("Original numbers:")
print(a)
print(a)
print("Comparison - greater")
print(np.greater(a, b))
print("Comparison - greater_equal")
print(np.greater_equal(a, b))
print("Comparison - less")
print(np.less(a, b))
print("Comparison - less_equal")
print(np.less_equal(a, b))

Original numbers:
[33 22 11]
[33 22 11]
Comparison - greater
[ True  True False]
Comparison - greater_equal
[ True  True False]
Comparison - less
[False False  True]
Comparison - less_equal
[False False  True]


# Question 2

In [3]:
c=print(np.zeros(10))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
d=print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
e=print(np.ones(10)*5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# Question 3

In [15]:
x=np.array([[1,3,5],[6,8,9],[10,20,30]])   


print("suum of array : ",np.sum(x))

print("sum of each rows : ",np.sum(x, axis=1))

print("sum of each coloumn : ",np.sum(x, axis=0))

suum of array :  92
sum of each rows :  [ 9 23 60]
sum of each coloumn :  [17 31 44]


# Question 4

In [19]:
print("Addition : ",np.add(10,20))

print("Subtraction : ",np.subtract(10,20))

print("Multiplication : ",np.multiply(10,20))

print("Division : ",np.divide(10,20))

Addition :  30
Subtraction :  -10
Multiplication :  200
Division :  0.5


# Question 5

In [32]:
print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180))

print("cosine: array of angles given in degrees")
print(np.cos(np.array((0. , 30. , 45. , 60. , 90.))* np.pi / 180.))

print("tangent: array of angles given in degrees")
print(np.tan(np.array((0. , 30. , 45. , 60. , 90.))* np.pi / 180.))

sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


# Question 6

In [2]:
import pandas as pd

In [4]:
z = {"name": ['Chandan','Avik','Aditya','Abhishek'],
  "score": [8.0,8.4,7.9,8.9],
   'attempts': [1, 3, 2, 3],
    'qualify': ['yes', 'no', 'yes', 'no']}
pd.DataFrame(z)

name  score  attempts qualify
0   Chandan    8.0         1     yes
1      Avik    8.4         3      no
2    Aditya    7.9         2     yes
3  Abhishek    8.9         3      no

# Question 7

In [13]:
print(y[['name','score']])

Select specific columns:
       name  score
0   Chandan    8.0
1      Avik    8.4
2    Aditya    7.9
3  Abhishek    8.9


# Question 8


In [1]:
stud_data1=pd.DataFrame({'student_id': ['S1', 'S2', 'S3', 'S4'],
         'name': ['Avik','Abhishek','Aditya','Chandan'],
        'marks': [200, 210, 190, 222]})

stud_data2=pd.DataFrame({'student_id': ['S1', 'S2', 'S3', 'S4'],
         'name': ['Luice','Man','Alex','Jack'],
        'marks': [300, 100, 187, 268]})

print("Original DataFrames:")
print(stud_data1)
print("-------------------------------------")
print(stud_data2)
print("\nJoin the said two dataframes along rows:")
result_data = pd.concat([stud_data1, stud_data2])
print(result_data)


NameError: name 'pd' is not defined

# Question 9