In [1]:
import numpy as np

In [5]:
ex1=np.zeros([9,2])
print(ex1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [14]:
var=np.array([[0,1,2],[2,4,6],[5,6,7]])

In [15]:
print(var)

[[0 1 2]
 [2 4 6]
 [5 6 7]]


In [17]:
var[1,1]=100

In [18]:
print(var)

[[  0   1   2]
 [  2 100   6]
 [  5   6   7]]


In [34]:
rowrank1=var[ 1: ]

In [35]:
print(rowrank1)

[[  2 100   6]
 [  5   6   7]]


In [47]:
colrank1=var[ :,2]
print(colrank1)

[2 6 7]


In [55]:
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(5)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3 4]


In [56]:
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [58]:
array1=5*np.random.random([2,5])

In [59]:
array1

array([[0.38191997, 1.78805026, 3.35034345, 0.7028172 , 3.2407597 ],
       [0.03656975, 4.05599992, 3.11993524, 0.71521705, 0.20858148]])

In [61]:
print(np.mean(array1))

1.7600194010374601


In [71]:
array2=np.array([4,5,1,22,56,21,19,27])


In [72]:
sorted=array2
sorted.sort()

In [73]:
print(sorted)

[ 1  4  5 19 21 22 27 56]


In [76]:
x1=np.zeros([3,3])
x1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
add_rows=np.array([1,0,3])

In [78]:
start=x1+add_rows
start

array([[1., 0., 3.],
       [1., 0., 3.],
       [1., 0., 3.]])

In [79]:
rowrank1

array([[  2, 100,   6],
       [  5,   6,   7]])

In [80]:
var

array([[  0,   1,   2],
       [  2, 100,   6],
       [  5,   6,   7]])

In [84]:
var.T

array([[  0,   2,   5],
       [  1, 100,   6],
       [  2,   6,   7]])

In [96]:
def arrange():
    
    str_of_wrds=input("Enter you string with comma : ")
    
    
    word=str_of_wrds.split(",")
    word.sort()
    word2=[]
    
    for i in word:
        word2.append(i)
    print(word2)
        
arrange()

Enter you string with comma : without,hello,bag,world
['bag', 'hello', 'without', 'world']


In [98]:
lst = [1, 2, 4, 6, 3, 7, 8] 
lst[-1]+1

9